FROM node:10
LABEL version="1.0"
LABEL description="FE Front App"
LABEL author_name="Fernando Karnagi"
LABEL author_email="fkarnagi@gmail.com"

RUN apt-get update
RUN apt-get -y install python-pip
RUN pip install awscli
RUN npm install -g yarn

RUN node -v
RUN npm -v
RUN git --version

RUN npm config set unsafe-perm true
RUN npm install -g @angular/cli@1.7.4 --unsafe-perm=true